test failed

diff --git a/.github/workflows/needs.yaml b/.github/workflows/needs.yaml
--- a/.github/workflows/needs.yaml
+++ b/.github/workflows/needs.yaml
@@ -14,8 +14,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Test the project
-        run: echo "Testing the project..."
-
+        run: |
+          echo "Test failed..."
+          exit 1 
+ 
   deploy:
     needs: test
     runs-on: ubuntu-latest
